"use client";

import NavigationPage from "@/components/Home/nav/page";
import FooterSection from "@/components/Home/FooterSection";

export default function TermsAndConditionsPage() {
  return (
    <>
      <NavigationPage />
      <main className="bg-white pt-32 pb-20">
        <div className="max-w-4xl mx-auto px-6">
          <h1 className="text-4xl font-bold mb-10 text-slate-900">
            Terms & Conditions
          </h1>
          <div className="space-y-6 text-slate-700 leading-8">
            <p className="whitespace-pre-line">
              {`This document is an electronic record prepared in accordance with the Information Technology Act, 2000 and
the rules framed thereunder. It is generated by a computer system and does not require any physical or
digital signature. These Terms and Conditions govern the use of the website https://lurnexa.in/journal
and all services offered by LURNEXA PUBLICATIONS PRIVATE LIMITED.
The website and related services are owned and operated by LURNEXA PUBLICATIONS PRIVATE LIMITED, having its registered
office at the officially declared business address. All communication related to the platform shall be made
through authorized email and contact channels published on the website.`}
            </p>
            <ul className="list-disc ml-6 space-y-4">
              <li>By accessing, browsing, registering, or using this platform in any manner, the user agrees to comply with these Terms and Conditions. Continued usage shall be treated as unconditional acceptance of these terms.</li>
              <li>Users must provide true, accurate, and complete information. They are responsible for maintaining confidentiality of login credentials and all activities under their account.</li>
              <li>All content including books, journals, designs, logos, graphics, and digital materials is the exclusive intellectual property of LURNEXA PUBLICATIONS PRIVATE LIMITED. Unauthorized reproduction is prohibited.</li>
              <li>Services are provided on an “as is” basis. The company does not guarantee accuracy, reliability, or uninterrupted access.</li>
              <li>Users shall not engage in unlawful, fraudulent, abusive, or misleading activities. Violations may result in suspension or termination.</li>
              <li>Payments must be made through authorized gateways. Prices and service charges may change without notice.</li>
              <li>LURNEXA PUBLICATIONS PRIVATE LIMITED reserves the right to modify policies, suspend services, or restrict access without prior notice.</li>
              <li>These terms are governed by Indian law and disputes fall under the jurisdiction of competent courts.</li>
            </ul>
          </div>
        </div>
      </main>
      <FooterSection />
    </>
  );
}
